name = "Rose Garden"
author = "VivvyInks"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b7399578e4141612a53a73c03c7faeef110a282810da4f14f77907461117eb7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
