name = "Rose Garden"
author = "VivvyInks"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb3f2346717627a56e76fce4fad5fbfce4de79c9abf94004cea0139df4c2a92"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
